app/urls.py
from django.urls import path
from .views import ListClubes, ListPeleadores,RatingList, get_comuna, DetallePelador, DetalleClub,Eventos

app_name = "app"

urlpatterns = [
    path('',Eventos.as_view(),name='eventos'),
    path('clubes/',ListClubes.as_view(),name='principal'),
    path('peleadores/',ListPeleadores.as_view(),name='peleadores'),
    path('rating/<int:pk>/',RatingList.as_view(),name='rating'),
    path('get_comuna/',get_comuna,name='comuna'),
    path('peleador/detalle/<int:pk>', DetallePelador.as_view(),name='detalle_peleador'),
    path('club/detalle/<int:pk>', DetalleClub.as_view(),name='detalle_club')
]

sword_core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'))
]

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from ckeditor.fields import RichTextField


class Eventos(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion = RichTextField(default='aqui texto')
    fecha = models.DateField()
    link_evento = models.CharField(max_length=400)

    def __str__(self):
        return self.titulo

    class Meta:
        verbose_name = "Evento"
        verbose_name_plural = "Eventos"


class Region(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Region"
        verbose_name_plural = "Regiones"
        ordering = ['-nombre']


class Comuna(models.Model):
    region = models.ForeignKey(
        Region, on_delete=models.CASCADE,related_name='comunas')
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Comuna"
        verbose_name_plural = "Comunas"
        ordering = ['-nombre']

    def __str__(self):
        return self.nombre


class Clubes(models.Model):
    nombre = models.CharField(max_length=50)
    region = models.ForeignKey(
        Region, on_delete=models.CASCADE)
    comuna = models.ForeignKey(
        Comuna, on_delete=models.CASCADE)
    logo = models.URLField(max_length=400, default='logo')
    imagen_perfil = models.URLField(max_length=400 ,default='aqui imagen perfil')
    description = RichTextField(default='aqui texto')

    class Meta:
        verbose_name = "Club"
        verbose_name_plural = "Clubes"

    def __str__(self) -> str:
        return self.nombre


class Categorias(models.Model):
    nombre = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"

    def __str__(self) -> str:
        return self.nombre


class Peleador(models.Model):
    FEMENINO = 'F'
    MASCULINO = 'M'
    SEXO_CHOICES = [
        (FEMENINO, 'Femenino'),
        (MASCULINO, 'Masculino')
    ]

    nombre = nombre = models.CharField(max_length=50)
    club = models.ForeignKey(Clubes, on_delete=models.CASCADE)
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES)

    class Meta:
        verbose_name = "Peleador"
        verbose_name_plural = "Peleadores"

    def __str__(self) -> str:
        return self.nombre


class Rating(models.Model):
    rank = models.IntegerField()
    categoria = models.ForeignKey(Categorias, on_delete=models.CASCADE)
    peleador = models.ForeignKey(Peleador, on_delete=models.CASCADE)
    rating = models.FloatField()
    rd = models.FloatField()

    class Meta:
        verbose_name = "Rating"
        verbose_name_plural = "Ratings"

    def __str__(self) -> str:
        return f'{self.rank} {self.categoria}'


class Usuario(AbstractUser):
    apellido_paterno = models.CharField(
        max_length=50, null=True, verbose_name="Apellido Paterno")
    apellido_materno = models.CharField(
        max_length=50, null=True, verbose_name="Apellido Materno")
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Rut: {self.username} - {self.apellido_materno} - {self.apellido_paterno}'

    class Meta:
        verbose_name = "Usuario"
        verbose_name_plural = "Usuarios"

app/forms.py
from django import forms
from .models import Clubes, Comuna


class ClubForm(forms.ModelForm):
    model = Clubes
    class Meta:
        fields = '__all__'
    class Media:
        js = ('js/main.js',)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['comuna'].queryset = Comuna.objects.none()

        if 'region' in self.data:
            try:
                region_id = int(self.data.get('region'))
                self.fields['comuna'].queryset = Comuna.objects.filter(region_id=region_id).order_by('nombre')
            except (ValueError, TypeError):
                pass  # Entrada no valida del cliente, ignora y regresa al conjunto de consulta vacia
        elif self.instance.pk:
            self.fields['comuna'].queryset = self.instance.region.comunas.order_by('nombre')

app/views.py
from django.shortcuts import render, HttpResponse
from django.views import View
from django.views.generic import ListView,DetailView
from django.contrib.auth.decorators import user_passes_test,login_required
import json
from .models import Clubes, Peleador,Rating, Comuna,Eventos

# Create your views here.


class Eventos(ListView):
    model = Eventos
    template_name = 'app/eventos.html'
    context_object_name = 'lista_eventos'
    


class ListClubes(ListView):
    model = Clubes
    template_name = 'app/index.html'
    context_object_name = 'lista_clubes'

  

class ListPeleadores(ListView):
    model = Peleador
    template_name = 'app/peleadores.html'
    context_object_name = 'lista_peleadores'




class RatingList(View):
    def get(self,request,pk):
        rating = Rating.objects.filter(categoria=pk)
        return render(request,'app/rating.html',{'lista_rating':rating})


class DetallePelador(DetailView):
    template_name = 'app/ficha_peleador.html'
    model = Peleador
    context_object_name = "detalle"

    def get_context_data(self, **kwargs):
        context = super(DetallePelador, self).get_context_data(**kwargs) # default
        context['ranking'] = Rating.objects.filter(peleador_id=self.object)
        return context


class DetalleClub(DetailView):
    template_name = 'app/ficha_club.html'
    model = Clubes
    context_object_name = "detalle"

    def get_context_data(self, **kwargs):
        context = super(DetalleClub, self).get_context_data(**kwargs) # default
        context['peleadores'] = Peleador.objects.filter(club_id=self.object)
        return context


    
@user_passes_test(lambda u: u.is_superuser)
@login_required
def get_comuna(request):
    id = request.GET.get('id','')
    result = list(Comuna.objects.filter(region_id=int(id)).values('id','nombre'))
    return HttpResponse(json.dumps(result), content_type="application/json")



    

app/templates/app/eventos.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}

<style>
    

body{
    background:#eee;
    }
    
    .white-bg {
        background-color: #ffffff;
    }
    
    .forum-item {
      margin: 10px 0;
      padding: 10px 0 20px;
      border-bottom: 1px solid #f1f1f1;
    }
    .forum-container,
    .forum-post-container {
      padding: 30px !important;
    }
    .forum-item small {
      color: #999;
    }
    .forum-item .forum-sub-title {
      color: rgb(20, 13, 13);
      margin-left: 50px;
    }
    .forum-title {
      margin: 15px 0 15px 0;
    }
  
    .forum-icon {
      float: left;
      width: 36px;
      margin-right: 20px;
      text-align: center;
    }
    a.forum-item-title {
      color: inherit;
      display: block;
      font-size: 18px;
      font-weight: 600;
    }
    a.forum-item-title:hover {
      color: inherit;
    }
    .forum-item.active a.forum-item-title {
      color: #d39e00 !important;
    }
    
    .ibox {
      clear: both;
      margin-bottom: 25px;
      margin-top: 0;
      padding: 0;
    }
    .ibox.collapsed .ibox-content {
      display: none;
    }
    .ibox.collapsed .fa.fa-chevron-up:before {
      content: "\f078";
    }
    .ibox.collapsed .fa.fa-chevron-down:before {
      content: "\f077";
    }
    .ibox:after,
    .ibox:before {
      display: table;
    }
    .ibox-title {
      -moz-border-bottom-colors: none;
      -moz-border-left-colors: none;
      -moz-border-right-colors: none;
      -moz-border-top-colors: none;
      background-color: #ffffff;
      border-color: #e7eaec;
      border-image: none;
      border-style: solid solid none;
      border-width: 3px 0 0;
      color: inherit;
      margin-bottom: 0;
      padding: 14px 15px 7px;
      min-height: 48px;
    }
    .ibox-content {
      background-color: #ffffff;
      color: inherit;
      padding: 15px 20px 20px 20px;
      border-color: #e7eaec;
      border-image: none;
      border-style: solid solid none;
      border-width: 1px 0;
    }
    .ibox-footer {
      color: inherit;
      border-top: 1px solid #e7eaec;
      font-size: 90%;
      background: #ffffff;
      padding: 10px 15px;
    }
    
    .message-input {
        height: 90px !important;
    }
    .form-control, .single-line {
        background-color: #FFFFFF;
        background-image: none;
        border: 1px solid #e5e6e7;
        border-radius: 1px;
        color: inherit;
        display: block;
        padding: 6px 12px;
        transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;
        width: 100%;
        font-size: 14px;
    }
    .text-navy {
        color: #1ab394;
    }
    .mid-icon {
        font-size: 66px !important;
    }
    .m-b-sm {
        margin-bottom: 10px;
    }
</style>
{% endblock %}

{% block contenido %}

<div class="container mt-3">
    <div class="row">
        <div class="col-lg-12">
            <div class="wrapper wrapper-content animated fadeInRight">
    
                <div class="ibox-content m-b-sm border-bottom">
                    <div class="p-xs">
                        <!-- <div class="pull-left m-r-md">
                            <i class="fa fa-globe text-navy mid-icon"></i>
                        </div> -->
                        <h2>Eventos de la Comunidad</h2>
                        <!-- <span>No se que poner en esta parte</span> -->
                    </div>
                </div>
    
                <div class="ibox-content forum-container">
                    <div class="forum-item active">
                        <div class="row">
                            {% for evento in lista_eventos%}
                            <div class="col-md-9">
                                <div class="forum-icon">
                                    <img src="{% static 'img/aviso.jpg'%}">
                                </div>
                                <a href="{{evento.link_evento}}" class="forum-item-title">{{evento.titulo}}:  {{evento.fecha}}</a>
                                <div class="forum-sub-title">
                                    {{evento.descripcion | safe }}
                                </div>
                            </div>
                            
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <!--fin ibox -->
            </div>
        </div>
    </div>
    </div>

{% endblock contenido %}

app/templates/app/ficha_club.html
{% extends 'base.html' %}

{% block contenido %}
<div class="container mt-3">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <img class="card-img-top" src="{{detalle.imagen_perfil}}" alt="{{detalle.nombre}}-logo">
                <ul class="list-group">
                    <li class="list-group-item"><strong>Nombre: </strong>{{detalle.nombre}}</li>
                    <li class="list-group-item"><strong>Region: </strong>{{detalle.region}}</li>
                    <li class="list-group-item"><strong>Comuna: </strong>{{detalle.comuna}}</li>
                  </ul>
                <div class="card-body">
                  <h5 class="card-title">Descripcion</h5>
                  <p class="card-text">{{detalle.description | safe}}</p>
                </div>
              </div>           
        </div>
        <div class="col-md-8">
            <table id="lista_club" class="table table-striped" style="width:100%">
                <thead class="table-dark">
                    <tr>    
                    <th>Nombre</th>
                    <th>Sexo</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in peleadores %}
                    <tr>
                        
                        <td>{{item.nombre}}</td>
                        <td>{{item.get_sexo_display}}</td>
                        
                        
                    </tr>
                    {% endfor %}
                </tbody>
                <!-- <tfoot>
                    <tr>
                        <th>Rank</th>
                        <th>Categoria</th>
                        <th>Peleador</th>
                        <th>Club</th>
                        <th>Rating</th>
                        <th>RD</th>
                    </tr>
                </tfoot> -->
            </table>
        </div>
     
    </div>
</div>

{% endblock contenido %}

app/templates/app/ficha_peleador.html
{% extends 'base.html' %}

{% block contenido %}
<div class="container mt-3">
    <div class="row">
        <div class="col-md-4">

            <ul class="list-group">
                <li class="list-group-item"><strong>Nombre: </strong>{{detalle.nombre}}</li>
                <li class="list-group-item"><strong>Club: </strong>{{detalle.club}}</li>
                <li class="list-group-item"><strong>Sexo: </strong>{{detalle.get_sexo_display}}</li>
              </ul>

            <h1></h1>
            <h1></h1>
            <h1></h1>
           
        </div>
        <div class="col-md-8">
            <table id="lista_club" class="table table-striped" style="width:100%">
                <thead class="table-dark">
                    <tr>
                        
                        <th>Categoria</th>
                        <th>Rank</th>
                        <th>Rating</th>
                        <th>RD</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in ranking %}
                    <tr>
                        
                        <td>{{item.categoria}}</td>
                        <td>{{item.rank}}</td>
                        <td>{{item.rating}}</td>
                        <td>{{item.rd}}</td>
                        
                    </tr>
                    {% endfor %}
                </tbody>
                <!-- <tfoot>
                    <tr>
                        <th>Rank</th>
                        <th>Categoria</th>
                        <th>Peleador</th>
                        <th>Club</th>
                        <th>Rating</th>
                        <th>RD</th>
                    </tr>
                </tfoot> -->
            </table>
        </div>
     
    </div>
</div>

      
{% endblock contenido %}

app/templates/app/index.html
{% extends 'base.html' %}


{% block contenido %}

<div class="container mt-3">
    
    <div class="row">
        <table id="lista_club" class="table table-striped" style="width:100%">
            <thead class="table-dark">
                <tr>
                    <th>Nombre</th>
                    <th>Logo</th>
                    <th>Region</th>
                    <th>Comuna</th>
                    <th></th>
                   
                </tr>
            </thead>
            <tbody>
                {% for item in lista_clubes %}
                <tr>
                    <td>{{item.nombre}}</td>
                    <td><a href="{% url 'app:detalle_club' item.id %}">
                        <img src="{{item.logo}}" class="rounded" alt="{{item.nombre}}-logo">
                    </a></td>
                    <td>{{item.region}}</td>
                    <td>{{item.comuna}}</td>
                    <td><a class="btn btn-primary" href="{% url 'app:detalle_club' item.id %}">Ficha</a></td>
                </tr>
                {% endfor %}
            </tbody>
            <!-- <tfoot>
                <tr>
                    <th>Nombre</th>
                    <th>Region</th>
                    <th>Comuna</th>
                </tr>
            </tfoot> -->
        </table>
    </div>
</div>


{% endblock %}

app/templates/app/peleadores.html
{% extends 'base.html' %}

{% block contenido %}

<div class="container mt-3">
    <div class="row">
        <table id="lista_club" class="table table-striped" style="width:100%">
            <thead class="table-dark">
                <tr>
                    <th>Nombre</th>
                    <th>Sexo</th>
                    <th>Club</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for item in lista_peleadores %}
                <tr>
                    <td>{{item.nombre}}</td>
                    <td>{{item.get_sexo_display}}</td>
                    <td><a href="{% url 'app:detalle_club' item.club.id %}">{{item.club}}</a></td>
                    <td><a class="btn btn-primary" href="{% url 'app:detalle_peleador' item.id %}">Ficha</a></td>
                </tr>
                {% endfor %}
            </tbody>
            <!-- <tfoot>
                <tr>
                    <th>Nombre</th>
                    <th>Sexo</th>
                    <th>Club</th>
                </tr>
            </tfoot> -->
        </table>
    </div>
</div>



{% endblock %}

app/templates/app/rating.html
{% extends 'base.html' %} {% block contenido %}

<div class="container mt-3">
  <div class="row">
    <h2>{{lista_rating.0.categoria}}</h2>
    <table id="lista_club" class="table table-striped" style="width: 100%">
      <thead class="table-dark">
        <tr>
          <th>Rank</th>
          <th>Peleador</th>
          <th>Club</th>
          <th>Rating</th>
          <th>RD</th>
        </tr>
      </thead>
      <tbody>
        {% for item in lista_rating %}
        <tr>
          <td>{{item.rank}}</td>
          <td>{{item.peleador.nombre}}</td>
          <td>{{item.peleador.club}}</td>
          <td>{{item.rating}}</td>
          <td>{{item.rd}}</td>
        </tr>
        {% endfor %}
      </tbody>
      <!-- <tfoot>
                <tr>
                    <th>Rank</th>
                    <th>Categoria</th>
                    <th>Peleador</th>
                    <th>Club</th>
                    <th>Rating</th>
                    <th>RD</th>
                </tr>
            </tfoot> -->
    </table>
  </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.datatables.net/v/bs5/dt-1.12.1/datatables.min.css"
    />

    {% block styles %}
    {% endblock %}
    <title>Peleitas con espadas</title>
  </head>
  <body>
    <nav
      class="navbar navbar-expand-lg navbar-dark bg-dark"
      aria-label="Ninth navbar example"
    >
      <div class="container-xl">
        <a class="navbar-brand" href="/">Peleas con espaditas</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarsExample07XL"
          aria-controls="navbarsExample07XL"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample07XL">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'app:principal' %}"
                >Clubes</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'app:peleadores' %}"
                >Peleadores</a
              >
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="dropdown07XL"
                data-bs-toggle="dropdown"
                aria-expanded="false"
                >Ranking</a
              >
              <ul class="dropdown-menu" aria-labelledby="dropdown07XL">
                {% for cat in lista_categorias %}
                <li>
                  <a class="dropdown-item" href="{% url 'app:rating' cat.id %}"
                    >{{cat.nombre}}</a
                  >
                </li>
                {% endfor %}
              </ul>
            </li>
          </ul>
          <!-- <form>
              <input class="form-control" type="text" placeholder="Search" aria-label="Search">
            </form> -->
        </div>
      </div>
    </nav>

    {% block contenido %} 
    
  

    {% endblock contenido %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="https://cdn.datatables.net/v/bs5/dt-1.12.1/datatables.min.js"
    ></script>
    <!-- <script src="https://cdn.datatables.net/plug-ins/1.12.1/i18n/es-ES.json"></script> -->
    {% block scripts %}
    <script>
      $.extend(true, $.fn.dataTable.defaults, {
        language: {
          decimal: ",",
          thousands: ".",
          info: "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
          infoEmpty:
            "Mostrando registros del 0 al 0 de un total de 0 registros",
          infoPostFix: "",
          infoFiltered: "(filtrado de un total de _MAX_ registros)",
          loadingRecords: "Cargando...",
          lengthMenu: "Mostrar _MENU_ registros",
          paginate: {
            first: "Primero",
            last: "Último",
            next: "Siguiente",
            previous: "Anterior",
          },
          processing: "Procesando...",
          search: "Buscar:",
          searchPlaceholder: "Término de búsqueda",
          zeroRecords: "No se encontraron resultados",
          emptyTable: "Ningún dato disponible en esta tabla",
          aria: {
            sortAscending:
              ": Activar para ordenar la columna de manera ascendente",
            sortDescending:
              ": Activar para ordenar la columna de manera descendente",
          },
          //only works for built-in buttons, not for custom buttons
          buttons: {
            create: "Nuevo",
            edit: "Cambiar",
            remove: "Borrar",
            copy: "Copiar",
            csv: "fichero CSV",
            excel: "tabla Excel",
            pdf: "documento PDF",
            print: "Imprimir",
            colvis: "Visibilidad columnas",
            collection: "Colección",
            upload: "Seleccione fichero....",
          },
          select: {
            rows: {
              _: "%d filas seleccionadas",
              0: "clic fila para seleccionar",
              1: "una fila seleccionada",
            },
          },
        },
      });
      $(document).ready(function () {
        $("#lista_club").DataTable();
      });
    </script>
    {% endblock %}
  </body>
</html>